version: "3.4"
services:
  database:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: panel
      MYSQL_USER: pterodactyl
      MYSQL_PASSWORD: thisisthepasswordforpterodactyl
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - db:/var/lib/mysql
    networks:
      network:
  cache:
    image: redis
    restart: always
    networks:
      network:
  php-fpm:
    image: joshuawalsh/pterodactyl-panel
    restart: always
    depends_on:
      - database
    volumes:
      - app:/var/www/html/
      - storage:/var/www/html/storage/
      - public:/var/www/html/public/
    environment:
      DB_HOST: database
      DB_PORT: 3306
      DB_DATABASE: panel
      DB_USERNAME: pterodactyl
      DB_PASSWORD: thisisthepasswordforpterodactyl
    networks:
      network:
  nginx:
    image: joshuawalsh/nginx-for-php-fpm
    restart: always
    depends_on:
      - php-fpm
    ports:
      - 5080:80
    volumes:
      - public:/var/www/html/
    networks:
      network:

volumes:
  public:
  db:
  storage:
  app:

networks:
  # This is just to give the network a nice name. The network
  # will appear as 'pterodactyl_network' instead of 'pterodactyl_default'
  network:
    driver: bridge